### ISSUE TITLE
Licence Missing

### ISSUE THREAD

**Issue by abdennebi** [redhat-scholars/istio-tutorial#127]
Hello,
I really appreciated your workshop ! 
Is it open source? I mean there no licence indicating how we can use it .
I would like to use this workshop in a professional context but also in conferences? Is that possible ?
Thank you for the answer,

**Comment by lordofthejars** [comment]
As far as I know, and following Red Hat philosophy and my feelings is that there should be no problem. Probably @burrsutter or @rafabene could give you a better answer, but my feelings is that there should be no problem.

**Comment by Abdennebi** [comment]
Thanks for your answer @lordofthejars. I told myself the same thing.
