### ISSUE TITLE
tcpdump: command not found

### ISSUE THREAD

**Issue by etoews** [redhat-scholars/istio-tutorial#257]
In the Enabling mTLS tutorial: https://learn.openshift.com/servicemesh/adv2-mtls

In Step 2 of 2, the following command fails

```
$ IP=$(ifconfig |grep inet |grep 10.|awk '{ print $2}'|sed -e 's/addr://g'); sudo tcpdump -vvvv -A -i eth0 '((dst port 8080) and (net '$IP'))'
sudo: tcpdump: command not found
```

**Comment by lordofthejars** [comment]
This might be because an update of Istio proxy docker images that they have deleted the `tcpdump`. I recommend checking the https://redhat-scholars.github.io/istio-tutorial/ for latest version
