### ISSUE TITLE
why do you use envoy

### ISSUE THREAD

**Issue by fizz12344321** [redhat-scholars/istio-tutorial#274]
Hi, i am reading your project and i love it, can i ask u a question, why do you use Envoy in your project. Can you tell me the purpose, the pros and cons of this. thank u so much

**Comment by kdubois** [comment]
Hi, Envoy is used by the Istio project, which is what we're using in this tutorial.  You can read more about it here: 
https://istio.io/latest/docs/ops/deployment/architecture/#:~:text=Istio's%20core%20components.-,Envoy,interact%20with%20data%20plane%20traffic.
